config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :merchants, only: [] do
    resource :dashboard, only: [:show]
    resources :items, only: [:index,:show, :edit, :update, :new, :create]
    resources :invoices, only: [:index, :show]
    resources :invoice_items, only: [:update]
  end

  namespace :admin do
    get "/", to: "dashboards#index"
    resources :merchants, only: [:index, :show, :edit, :update, :new, :create]
    resources :invoices, only: [:index, :show, :update]
  end
end

app/views/admin/_admin_header.html.erb
<header>
  <%= link_to "Dashboard", admin_index_path %>
  <%= link_to "Merchants", admin_merchants_path %>
  <%= link_to "Invoices", admin_invoices_path %>
</header>

app/views/admin/_admin_nav.html.erb
<h1 style="float:left; margin:20px;">Admin Dashboard</h1>
<h3 style="float:right; background-color:lightgrey; margin:20px;"><%= link_to "Dashboard", admin_index_path %>
<%= link_to "Merchants", admin_merchants_path %>
<%= link_to "Invoices", admin_invoices_path %></h3>

app/views/admin/dashboard.html.erb
<h1><%= "Admin Dashboard" %></h1>

app/views/admin/index.html.erb
<%= render "shared/admin_header" %>

<div id = "top_customers">
  <h3>Top Customers</h3>
  <ol>
  <% @customers.top_five_customers.each do |customer| %>
    <div id = "top_customer<%= customer.id %>">
      <li><p><%= customer.first_name %> <%= customer.last_name %> - <%= customer.successful_transactions_count%> purchases</p>
      </li>
    </div>
  <% end %>
  </ol>
</div>

<section class="incomplete_invoices">
  <h3>Incomplete Invoices</h3>
  <% @invoices.invoices_with_unshipped_items_oldest_to_newest.each do |invoice| %>
    <div id="invoice_<%= invoice.id %>">
      <p><%= link_to "Invoice ##{invoice.id} - #{invoice.created_at.strftime('%A, %B %d, %Y')}", "/admin/invoices/#{invoice.id}", data: {turbo: false} %></p>
    </div>
  <% end %>
</section>