config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :merchants, only: [] do
    resource :dashboard, only: [:show]
    resources :items, only: [:index,:show, :edit, :update, :new, :create]
    resources :invoices, only: [:index, :show]
    resources :invoice_items, only: [:update]
  end

  namespace :admin do
    get "/", to: "dashboards#index"
    resources :merchants, only: [:index, :show, :edit, :update, :new, :create]
    resources :invoices, only: [:index, :show, :update]
  end
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :items
  has_many :invoices, through: :items
  has_many :customers, through: :invoices
  has_many :transactions, through: :customers
  has_many :invoice_items, through: :items

  validates :name, presence: true

  enum status: {
  disable: 0,
  enable: 1
  }
  # SELECT customers.*, COUNT(transactions.id) as "transaction_count"
  # FROM transactions
  # INNER JOIN invoices ON transactions.invoice_id = invoices.id
  # INNER JOIN invoice_items ON invoices.id = invoice_items.invoice_id
  # INNER JOIN items ON invoice_items.item_id = items.id
  # INNER JOIN customers ON customers.id = invoices.customer_id
  # WHERE items.merchant_id = 1 AND transactions.result = 'success'
  # GROUP BY customers.id
  # ORDER BY COUNT(transactions.id) DESC
  # LIMIT 5
  def top_customers
    customers
      .joins(:transactions)
      .where(transactions: { result: "success" })
      .group("customers.id")
      .order("count(transactions.id) DESC")
      .limit(5)
      .select("customers.*", "COUNT(transactions.id) AS transaction_count")
  end

  def items_ready_to_ship
    invoice_items
      .joins(:invoice)
      .where(invoice_items: {status: "packaged"})
      .order('invoices.created_at ASC')
  end

  def calculate_top_items
    self.items
        .select('items.*, SUM(invoice_items.quantity * invoice_items.unit_price) AS total_revenue')
        .joins(:invoice_items)
        .joins(invoices: :transactions) # Change 'invoice' to 'invoices'
        .where(transactions: { result: 'success' })
        .group('items.id')
        .order('total_revenue DESC')
        .limit(5)
  end

  def total_revenue
    invoice_items.sum('invoice_items.quantity * invoice_items.unit_price')
  end

  def self.top_merchants
    self.select('merchants.*, SUM(invoice_items.quantity * invoice_items.unit_price) AS total_revenue')
        .joins(:items)
        .joins(:invoice_items)
        .joins(invoices: :transactions)
        .where(transactions: { result: 'success' })
        .group('merchants.id', 'merchants.name')
        .order('total_revenue DESC')
        .limit(5)
  end

#   SELECT
#   DATE_TRUNC('day', invoices.created_at) AS created_at_day,
#   merchants.id,
#   SUM(invoice_items.quantity * invoice_items.unit_price) AS total_revenue
# FROM
#   invoices
# INNER JOIN invoice_items ON invoices.id = invoice_items.invoice_id
# INNER JOIN items ON invoice_items.item_id = items.id
# INNER JOIN merchants ON items.merchant_id = merchants.id
# INNER JOIN transactions ON transactions.invoice_id = invoices.id
# WHERE
#   transactions.result = 'success'
# GROUP BY
#   created_at_day,
#   merchants.id
# ORDER BY
#   total_revenue DESC
# LIMIT 1;

  def best_day
    self.invoices
        .joins(items: :invoice_items)
        .joins(:transactions)
        .where(transactions: { result: 'success' })
        .group("created_at_day")
        .order(Arel.sql("SUM(invoice_items.quantity * invoice_items.unit_price) DESC"))
        .limit(1)
        .pluck(Arel.sql("DATE_TRUNC('day', invoices.created_at) AS created_at_day"))
        .first
        # .pluck("invoices.created_at as created_at_day").first
  end

  # def calculate_topitems_date(top_items)
  #   top_items.map do |item|
  #     top_selling_date = item.invoices
  #                            .joins(:transactions)
  #                            .where(transactions: { result: 'success' })
  #                            .group(:created_at)
  #                            .order(Arel.sql('COUNT(*) DESC, created_at DESC'))
  #                            .limit(1)
  #                            .pluck(:created_at)
  #                            .first


  #     formatted_date = top_selling_date.strftime("%Y-%m-%d")

  #     [item, formatted_date]
  #   end
  # end


  def calculate_topitems_date(top_items)
    top_items.map do |item|
      top_selling_date = item.invoices
                             .joins(:transactions)
                             .where(transactions: { result: 'success' })
                             .group(:created_at)
                             .order(Arel.sql('SUM(invoice_items.quantity * invoice_items.unit_price) DESC, created_at DESC'))
                             .limit(1)
                             .pluck(:created_at)
                             .first

      formatted_date = top_selling_date.strftime("%Y-%m-%d")

      [item, formatted_date]
    end
  end

end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < ApplicationController
    def index
        @merchants = Merchant.all
        @top_merchants = Merchant.top_merchants
    end

    def show
        @merchant = Merchant.find(params[:id])
    end

    def new
        @merchant = Merchant.new
    end

    def create
        @merchant = Merchant.new(merchant_params)
        if @merchant.save
            redirect_to admin_merchants_path
        else
            flash[:alert] = "Error. Please enter a name."
            render :new
        end
    end

    def edit
        @merchant = Merchant.find(params[:id])
    end

    def update
        merchant = Merchant.find(params[:id])

        merchant.update(merchant_params)

        if merchant_params[:name]
            flash[:notice] = "Merchant information is updated successfully"
            redirect_to admin_merchant_path(merchant)
        end

        if merchant_params[:status]
            flash[:notice] = "Merchant status is updated successfully"
            redirect_to admin_merchants_path
        end
    end

    private

    def merchant_params
        params.require(:merchant).permit(:name, :status)
    end
end

app/controllers/merchant/dashboard_controller.rb
class Merchant::DashboardController < ApplicationController 
  layout 'merchant/layouts/dashboard'
  
  def index 
    @merchant = Merchant.find(params[:merchant_id])
    @customers = Customer.all
  end
end

app/controllers/merchant/invoice_items_controller.rb
class Merchant::InvoiceItemsController < ApplicationController 
    def update
        @invoice_item = InvoiceItem.find(params[:invoice_item_id])
        @invoice_item.update(status: params[:status])
        redirect_to "/merchants/#{params[:merchant_id]}/invoices/#{@invoice_item.invoice_id}"
    end
end

app/controllers/merchant/invoices_controller.rb
class Merchant::InvoicesController < ApplicationController 
  def index 
    @merchant = Merchant.find(params[:merchant_id])
    @invoice_items = @merchant.invoice_items
  end
  
  def show
    @invoice = Invoice.find(params[:id])
    @customer = Customer.find(@invoice.customer_id)
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < ApplicationController 
    def index 
      @merchant = Merchant.find(params[:merchant_id])
      @items = @merchant.items
    end

  def show 
      @item = Item.find(params[:id])
      @merchant = @item.merchant
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if( params.has_key?(:name) && params.has_key?(:description) && params.has_key?(:unit_price) ) 
      item.update(name: params[:name], description: params[:description], unit_price: params[:unit_price])
      redirect_to "/merchants/#{item.merchant_id}/items/#{item.id}"
      flash[:notice] = "Update successful!"
    elsif( params.has_key?(:status) )
      if item.status == "Enabled"
        item.update(status: "Disabled")
      else
        item.update(status: "Enabled")
      end
      redirect_to "/merchants/#{item.merchant_id}/items"
    end
  end

  def new
    @merchant = Merchant.find(params[:merchant_id])
  end

  def create
    merchant = Merchant.find(params[:merchant_id])
    if params[:name].length > 0 && params[:description].length > 0 && params[:unit_price].length > 0
      merchant.items.create(name: params[:name], description: params[:description], unit_price: params[:unit_price], merchant_id: params[:merchant_id])
    end
    redirect_to "/merchants/#{params[:merchant_id]}/items"
  end
end

app/controllers/merchants/dashboard_controller.rb
class Merchants::DashboardController < ApplicationController
    def index
        @merchant = Merchant.find(params[:merchant_id])
    end
end

app/controllers/merchants/invoices_controller.rb
class Merchants::InvoicesController < ApplicationController
  def index
    @merchant = Merchant.find(params[:merchant_id])
  end
  
  def show
    @invoice = Invoice.find(params[:id])
    @merchant = Merchant.find(params[:merchant_id])
    # require'pry';binding.pry
  end
end

app/controllers/merchants/items/status_controller.rb
class Merchants::Items::StatusController < ApplicationController
  def update
    merchant = Merchant.find(params[:merchant_id])
    item = Item.find(params[:item_id])
    item.update({
      status: params[:status]
    })

    redirect_to merchant_items_path(merchant)
  end
end

app/controllers/merchants/items_controller.rb
class Merchants::ItemsController < ApplicationController
  def show
    @merchant = Merchant.find(params[:merchant_id])
    @item = Item.find(params[:id])
  end

  def index
    @merchant = Merchant.find(params[:merchant_id])
  end

  def edit
    @merchant = Merchant.find(params[:merchant_id])
    @item = Item.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:merchant_id])
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to merchant_item_path(@merchant, @item)
      flash[:alert] = "Item successfully updated"
    else
      # should use render here, need to do research on how (can do in refactor)
      redirect_to edit_merchant_item_path(@merchant, @item)
      flash[:alert] = "Error: #{error_message(@item.errors)}"
    end
  end

  def new
    @merchant = Merchant.find(params[:merchant_id])
  end

  def create
    merchant = Merchant.find(params[:merchant_id])
    item = merchant.items.new(item_params)
    if item.save
      redirect_to merchant_items_path(merchant)
    else
      redirect_to new_merchant_item_path
      flash[:alert] = "Error: #{error_message(item.errors)}"
    end
  end
  
  private
  
  def item_params
    params.permit(:name, :description, :unit_price, :merchant_id)
  end
end
  

app/controllers/merchants/merchants_controller.rb
class MerchantsController < ApplicationController
  # def index
  #   @merchants = Merchant.all
  # end

  # def show
  #   @merchant = Merchant.find(params[:id])
  # end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def dashboard
    @merchant = Merchant.find(params[:id])
  end
end

app/views/admins/merchants/edit.html.erb
<section id="header"> 
  <h3 style="float:left; width:50%; text-align:left;">Admin Dashboard</h3>
</section>
<section id="content" style="clear:both">
  <div id="merchant_info" style="width:100%; padding:20px;">
    <h4 style="text-align: center; background-color: #eee; padding: 10px; height: 100%"><%= @edit_admins_merchant.name %></h4>
    <%= form_with model: @edit_admins_merchant, url: admin_merchant_path(@edit_admins_merchant), id: "merchant_edit_form", local: true do |form| %>
      <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</section>

app/views/admins/merchants/index.html.erb
<section id="header"> 
  <h3 style="float:left; width:50%; text-align:left;">Admin Dashboard</h3>
</section>
<section id="content" style="clear:both">
  <div>
    <%= link_to "New Merchant", "#{new_admin_merchant_path}" %>
  </div>
  <div id="merchant_list" style="float:left; width:50%; padding:20px;">
    <h2>Merchant List</h2>
    <h4>Enabled Merchants</h4>
    <ol id = "enabled_merchants">
      <% @merchants.each do |merchant| %>
        <% if merchant.status == true %>
          <li>
            <%= link_to "#{merchant.name}", admin_merchant_path(merchant.id) %><%= button_to merchant.status ? "Disable" : "Enable", toggle_status_admin_merchant_path(merchant.id), method: :patch, id: "#{merchant.id}_button" %>
          </li>
        <% end %>
      <% end %>
    </ol>
    <h4>Disabled Merchants</h4>
    <ol id = "disabled_merchants">
      <% @merchants.each do |merchant| %>
        <% if merchant.status == false %>
          <li>
            <%= link_to "#{merchant.name}", admin_merchant_path(merchant.id) %><%= button_to merchant.status ? "Disable" : "Enable", toggle_status_admin_merchant_path(merchant.id), method: :patch, id: "#{merchant.id}_button" %>
          </li>
        <% end %>
      <% end %>
    </ol>
  </div>

  <div id="top_merchants" style="float:right; width:50%; padding:20px;">
    <h2>Top Merchants</h2>
    <% @top_merchants.each do |merchant| %>
  <ol>
    <li>
      <%= link_to merchant.name, admin_merchant_path(merchant) %>
      — <%= number_to_currency(merchant.revenue, unit: '$') %> in sales
      <br>
        Top selling date for <%= merchant.name%> was <%=merchant.top_selling_date%>
      
    </li>
  </ol>
<% end %>
  </div>
</section>

app/views/admins/merchants/new.html.erb
<section id="header"> 
  <h3 style="float:left; width:50%; text-align:left;">Admin Dashboard</h3>
</section>
<section id="content" style="clear:both">
  <%= form_with model: @merchant, url: admin_merchants_path, id: "new_merchant_form", local: true do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <%= form.hidden_field :status, value: false %>
  <p>
    <%= form.submit value: "Submit" %>
  </p>
  <% end %>

</section>

app/views/admins/merchants/show.html.erb
<section id="header"> 
  <h3 style="float:left; width:50%; text-align:left;">Admin Dashboard</h3>
</section>
<section id="content" style="clear:both">
  <div id="merchant_info" style="width:100%; padding:20px;">
    <h4 style="text-align: center; background-color: #eee; padding: 10px; height: 100%"><%= @merchant.name %></h4>
    <% if flash[:notice].present? %>
      <div class="flash-notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <p><%= link_to "Update Merchant", edit_admin_merchant_path %></p>
  </div>
</section>