config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :merchants, only: [] do
    resource :dashboard, only: [:show]
    resources :items, only: [:index,:show, :edit, :update, :new, :create]
    resources :invoices, only: [:index, :show]
    resources :invoice_items, only: [:update]
  end

  namespace :admin do
    get "/", to: "dashboards#index"
    resources :merchants, only: [:index, :show, :edit, :update, :new, :create]
    resources :invoices, only: [:index, :show, :update]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
   def index
      @customers = Customer.all
      @incomplete_invoices = Invoice.incomplete_invoices
   end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
    include Admin::DashboardsHelper
    def index
        @top_customers = Customer.top_customers
        @incomplete_invoices = Invoice.incomplete_invoices
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @merchant = Merchant.find(params[:merchant_id])
    @top_customers = @merchant.top_customers
    @items_ready_to_ship = @merchant.items_ready_to_ship
  end
end

app/controllers/merchant/dashboard_controller.rb
class Merchant::DashboardController < ApplicationController 
  layout 'merchant/layouts/dashboard'
  
  def index 
    @merchant = Merchant.find(params[:merchant_id])
    @customers = Customer.all
  end
end

app/controllers/merchants/dashboard_controller.rb
class Merchants::DashboardController < ApplicationController
    def index
        @merchant = Merchant.find(params[:merchant_id])
    end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
    def format_created_at(created_at)
      created_at.strftime("%A, %B %d, %Y")
    end
  end

app/views/admin/dashboards/dashboard.html.erb
<h1>Admin Dashboard</h1>

<%= link_to "admin merchants", "/admin/merchants" %><br>
<%= link_to "admin invoices", "/admin/invoices" %>

<h2>Best Customers</h2>
<% @customers.top_5_customers.each do |customer|%>
  <p>
    Name: <%= customer.first_name %>, <%= customer.last_name %><br>
    Transactions made: <%= customer.transaction_counter %>
  </p>
<% end %>

<section id = "Incomplete_Invoices">
  <h2> Incomplete Invoices </h2>
  <% @invoices.incomplete_orders.each do |invoice| %>
    <%= link_to "ID: #{invoice.id}", "/admin/invoices/#{invoice.id}" %><br>
    <%= invoice.created_at.strftime("%A, %B %d, %Y, %I:%M:%N") %><br>
  <% end %>
</section>

app/views/admin/dashboards/index.html.erb
<h1>Little Etsy Shop Admin Dashboard</h1>
<%= link_to "Merchants", admin_merchants_path %>
<%= link_to "Invoices", admin_invoices_path %>

<h3>Little Etsy's Favorite Customers</h3>
    <ol>
        <% @top_customers.each do |top_customer| %>
            <section id="top_customer-<%= top_customer.id %>">
            <li> <%= "#{top_customer.first_name} #{top_customer.last_name}: #{top_customer.transaction_count} transactions" %></li>
            </section>
        <% end %>   
    </ol>


<h3>Little Etsy's Incomplete Invoices</h3>
<ol>
        <% @incomplete_invoices.each do |invoice_item| %>
            <section id="invoice_item-<%= invoice_item.invoice_id %>">
            <li> <%=link_to "Invoice: #{invoice_item.invoice_id}", admin_invoice_path(invoice_item.invoice_id)%> <%=format_created_at(invoice_item.invoice.created_at)%></li>
            </section>
        <% end %>   
    </ol>